### ISSUE TITLE
UnboundLocalError: local variable 'do_shuffle' referenced before assignment

### ISSUE THREAD

**Issue by LuoBingjun** [tingyu215/TS-LLaVA#1]
Hello, thank you for sharing your excellent project.

When I evaluated it on the multiple-choice QA benchmark EgoSchema, I found that there is an error occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/TS-LLaVA/scripts/infer_video/run_inference_multiple_choice_qa.py", line 181, in <module>
    run_inference(args)
  File "/root/autodl-tmp/TS-LLaVA/scripts/infer_video/run_inference_multiple_choice_qa.py", line 124, in run_inference
    output = llava_inference(
  File "/root/autodl-tmp/TS-LLaVA/scripts/infer_video/run_inference_multiple_choice_qa.py", line 49, in llava_inference
    output_ids = model.generate(
  File "/root/autodl-tmp/miniconda/bin/eval/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/TS-LLaVA/llava/model/language_model/llava_llama.py", line 125, in generate
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/root/autodl-tmp/TS-LLaVA/llava/model/llava_arch.py", line 584, in prepare_inputs_labels_for_multimodal
    image_features = self.grid_aggregation(images)
  File "/root/autodl-tmp/TS-LLaVA/llava/model/llava_arch.py", line 441, in grid_aggregation
    sampled_images = create_image_grid(sampled_images, shuffling=do_shuffle)
UnboundLocalError: local variable 'do_shuffle' referenced before assignment

**Comment by tingyu215** [comment]
Hi,

Thank you for your interest in our project, and I apologize for the delayed response—I’ve been occupied with a busy schedule.

I’ve updated the code and added ``else: do_shuffle = False``, so it should work fine now. The ``do_shuffle`` option is not used in our method and was only added to test whether shuffling affects the results. You can also delete the code related to it if you prefer, as it does not impact the results.
